<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.enelson.sopli.lib</groupId>
        <artifactId>soplib-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>
    <artifactId>soplib-shade</artifactId>
    <packaging>jar</packaging>
    <name>SopLib</name>

    <dependencies>
        <dependency>
            <groupId>net.enelson.sopli.lib</groupId>
            <artifactId>soplib-core</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.enelson.sopli.lib</groupId>
            <artifactId>soplib-impl-1.20.4</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.enelson.sopli.lib</groupId>
            <artifactId>soplib-impl-1.21.1</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.enelson.sopli.lib</groupId>
            <artifactId>soplib-impl-1.21.11</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <!-- Spigot для компиляции main-класса -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.20.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

	<build>
		<finalName>SopLib-${project.version}</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<minimizeJar>false</minimizeJar>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
