<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.enelson.sopli.lib</groupId>
        <artifactId>soplib-parent</artifactId>
        <version>1.0.2</version>
        <relativePath>..</relativePath>
    </parent>
    <artifactId>soplib-impl-1.20.4</artifactId>
    <packaging>jar</packaging>
    <name>SopLib Impl 1.20.4</name>

    <dependencies>
        <dependency>
            <groupId>net.enelson.sopli.lib</groupId>
            <artifactId>soplib-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.20.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
	    <dependency>
	        <groupId>de.tr7zw</groupId>
	        <artifactId>item-nbt-api-plugin</artifactId>
	        <version>2.15.5</version>
	        <scope>provided</scope>
	    </dependency>
    </dependencies>
</project>
